# Server
server.port=8080

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/leave_management_db
spring.data.mongodb.database=leave_management_db

# JWT
app.jwt.secret=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
app.jwt.expiration-ms=86400000

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.com.lms=DEBUG

# CORS
app.cors.allowed-origins=http://localhost:5173
